[build]
  publish = "legacy"

[[redirects]]
  from   = "/api/openrouter"
  to     = "/.netlify/functions/openrouter-proxy"
  status = 200

[[redirects]]
  from   = "/api/tavily-sources"
  to     = "/.netlify/functions/tavily-sources"
  status = 200

[[redirects]]
  from   = "/api/supabase-config"
  to     = "/.netlify/functions/supabase-config"
  status = 200
